# See config.example.yml for documentation.
object_base: orig/GAMEID
object: sys/main.dol
hash: 0123456789abcdef0123456789abcdef01234567
symbols: config/GAMEID/symbols.txt
splits: config/GAMEID/splits.txt
# Change this to match the linker verison.
# See config.example.yml for a list.
mw_comment_version: 11

modules:
- object: files/module.rel
  hash: 0123456789abcdef0123456789abcdef01234567
  symbols: config/GAMEID/module/symbols.txt
  splits: config/GAMEID/module/splits.txt
